#!/usr/bin/env python3
"""
Imports NBA free agents from a Fantrax CSV export into fantasy_basketball_db.

USAGE
    python scripts/import_nba_free_agents.py "C:/path/to/Fantrax-Players-The Dynasty Association.csv" > /tmp/nba_fa_import.sql
    docker exec -i fantasy_postgres psql -U admin -d fantasy_basketball_db < /tmp/nba_fa_import.sql

Behavior:
- Reads the CSV (1198 rows: 1 header + ~1197 free agents).
- Inserts each row as a free agent (team_id=NULL, fa_status=NULL).
- Uses ON CONFLICT (fantrax_id) DO NOTHING — any FA whose Fantrax ID already exists in
  the players table (i.e., already rostered from the xlsx import) is silently skipped,
  so re-runs are safe and dual-listed players keep their team assignment.
- Does NOT touch existing rostered players.
"""

import csv
import re
import sys
from pathlib import Path

LEAGUE_ID = "55555555-5555-5555-5555-555555555555"


def sql_str(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def normalize_position(pos):
    if not pos:
        return None
    parts = [p.strip().upper() for p in pos.split(",") if p.strip()]
    return ",".join(parts) if parts else None


def normalize_name(name):
    if not name:
        return ""
    return re.sub(r"\s+", " ", name).strip()


def parse_age(s):
    if not s:
        return "NULL"
    try:
        return str(int(float(s)))
    except (ValueError, TypeError):
        return "NULL"


def main():
    if len(sys.argv) < 2:
        sys.stderr.write("usage: import_nba_free_agents.py <path-to-csv>\n")
        sys.exit(2)
    path = Path(sys.argv[1])
    if not path.exists():
        sys.stderr.write(f"file not found: {path}\n")
        sys.exit(2)

    with open(path, encoding="utf-8-sig", newline="") as f:
        rows = list(csv.DictReader(f))

    sys.stderr.write(f"Read {len(rows)} rows from {path.name}\n")

    print("-- Generated by scripts/import_nba_free_agents.py")
    print(f"-- Source: {path.name}")
    print("BEGIN;")
    print()
    print("-- ON CONFLICT (fantrax_id) DO NOTHING relies on uniq_players_fantrax_id")
    print("-- (partial unique index from migration 004). Players already on a team")
    print("-- with the same fantrax_id will be skipped — they keep their assignment.")
    print()

    inserted = 0
    skipped_no_id = 0
    for r in rows:
        fid = (r.get("ID") or "").strip()
        if not fid:
            skipped_no_id += 1
            continue
        name = normalize_name(r.get("Player") or "")
        if not name:
            skipped_no_id += 1
            continue

        parts = name.split(" ", 1)
        first = parts[0]
        last = parts[1] if len(parts) > 1 else ""

        position = normalize_position(r.get("Position") or "")
        rl_team = (r.get("Team") or "").strip()
        if rl_team == "(N/A)":
            rl_team = ""

        age = parse_age(r.get("Age") or "")

        cols = [
            "league_id", "team_id",
            "first_name", "last_name", "position", "real_life_team",
            "fantrax_id", "age",
            "on_two_way", "on_g_league", "on_active_roster",
            "fa_status",
        ]
        vals = [
            f"'{LEAGUE_ID}'", "NULL",
            sql_str(first), sql_str(last), sql_str(position), sql_str(rl_team),
            sql_str(fid), age,
            "FALSE", "FALSE", "FALSE",
            "NULL",  # fa_status NULL = available; pending_bid / on_waivers come from bid system later
        ]
        print(
            f"INSERT INTO players ({', '.join(cols)}) VALUES ({', '.join(vals)})"
            f" ON CONFLICT (fantrax_id) WHERE fantrax_id IS NOT NULL DO NOTHING;"
        )
        inserted += 1

    print()
    print(f"-- Emitted {inserted} INSERTs ({skipped_no_id} skipped: no fantrax_id or name)")
    print("COMMIT;")
    sys.stderr.write(f"\nDone. {inserted} INSERT statements emitted.\n")


if __name__ == "__main__":
    main()
